import asyncio

from grpclib.client import Channel

# generated by protoc betterproto
from challenges import ChallengeStub


async def main():
    channel = Channel('127.0.0.1', 50051)
    stub = ChallengeStub(channel)

    challenge = await stub.create(name='Mr. Easy')
    print(challenge.id, challenge.name)

    async for challenge in stub.list():
        print(challenge.id, challenge.name)

    channel.close()


if __name__ == '__main__':
    asyncio.run(main())
