# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: structures.proto, api.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import AsyncGenerator

import betterproto
import grpclib

from google.protobuf import empty_pb2


@dataclass
class ChallengeRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass
class ChallengeResponse(betterproto.Message):
    id: int = betterproto.int32_field(1)
    name: str = betterproto.string_field(2)


class ChallengeStub(betterproto.ServiceStub):
    async def create(self, *, name: str = "") -> ChallengeResponse:
        request = ChallengeRequest()
        request.name = name

        return await self._unary_unary(
            "/challenges.Challenge/create", request, ChallengeResponse,
        )

    async def list(self) -> AsyncGenerator[ChallengeResponse, None]:
        """
        rpc bulk_create (stream ChallengeRequest) returns (stream
        ChallengeResponse) {}
        """

        request = empty_pb2.Empty()

        async for response in self._unary_stream(
            "/challenges.Challenge/list", request, ChallengeResponse,
        ):
            yield response
