import asyncio

from google.protobuf.empty_pb2 import Empty
from grpclib.client import Channel

# generated by protoc mypy
from mypy_way.api_grpc import ChallengeStub
from mypy_way.api_pb2 import ChallengeRequest, ChallengeResponse


async def main():
    channel = Channel('127.0.0.1', 50051)
    stub = ChallengeStub(channel)

    challenge: ChallengeResponse = await stub.create(ChallengeRequest(name='Mr. Easy'))
    print(challenge.id, challenge.name)

    async with stub.bulk_create.open() as stream:
        for i in range(2):
            await stream.send_message(ChallengeRequest(name=f'({i}) Mr. Bulk Easy'))
        await stream.end()
        async for challenge in stream:
            print(challenge.id, challenge.name)

    async with stub.list.open() as stream:
        await stream.send_message(Empty())
        async for challenge in stream:
            print(challenge.id, challenge.name)

    channel.close()


if __name__ == '__main__':
    asyncio.run(main())
