import asyncio

import purerpc
from google.protobuf.empty_pb2 import Empty

# generated by protoc purerpc
from purerpc_way.api_pb2 import ChallengeRequest
from purerpc_way.api_grpc import ChallengeStub


async def main():
    async with purerpc.insecure_channel("localhost", 50051) as channel:
        stub = ChallengeStub(channel)

        challenge = await stub.create(ChallengeRequest(name='Mr. Easy'))
        print(challenge.id, challenge.name)

        async def challenge_requests(name):
            for i in range(2):
                yield ChallengeRequest(name=f'({i} {name}')

        async for challenge in stub.bulk_create(challenge_requests('Mr. Bulk Easy')):
            print(challenge.id, challenge.name)

        async for challenge in stub.list(Empty()):
            print(challenge.id, challenge.name)


if __name__ == '__main__':
    asyncio.run(main())
