# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.empty_pb2
from grpclib_way import api_pb2


class ChallengeBase(abc.ABC):

    @abc.abstractmethod
    async def create(self, stream: 'grpclib.server.Stream[api_pb2.ChallengeRequest, api_pb2.ChallengeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def bulk_create(self, stream: 'grpclib.server.Stream[api_pb2.ChallengeRequest, api_pb2.ChallengeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def list(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, api_pb2.ChallengeResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/challenges.Challenge/create': grpclib.const.Handler(
                self.create,
                grpclib.const.Cardinality.UNARY_UNARY,
                api_pb2.ChallengeRequest,
                api_pb2.ChallengeResponse,
            ),
            '/challenges.Challenge/bulk_create': grpclib.const.Handler(
                self.bulk_create,
                grpclib.const.Cardinality.STREAM_STREAM,
                api_pb2.ChallengeRequest,
                api_pb2.ChallengeResponse,
            ),
            '/challenges.Challenge/list': grpclib.const.Handler(
                self.list,
                grpclib.const.Cardinality.UNARY_STREAM,
                google.protobuf.empty_pb2.Empty,
                api_pb2.ChallengeResponse,
            ),
        }


class ChallengeStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.create = grpclib.client.UnaryUnaryMethod(
            channel,
            '/challenges.Challenge/create',
            api_pb2.ChallengeRequest,
            api_pb2.ChallengeResponse,
        )
        self.bulk_create = grpclib.client.StreamStreamMethod(
            channel,
            '/challenges.Challenge/bulk_create',
            api_pb2.ChallengeRequest,
            api_pb2.ChallengeResponse,
        )
        self.list = grpclib.client.UnaryStreamMethod(
            channel,
            '/challenges.Challenge/list',
            google.protobuf.empty_pb2.Empty,
            api_pb2.ChallengeResponse,
        )
