# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='challenges',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tapi.proto\x12\nchallenges\x1a\x1bgoogle/protobuf/empty.proto\" \n\x10\x43hallengeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x11\x43hallengeRequest2\x12\r\n\x05nameq\x18\x01 \x01(\t\"-\n\x11\x43hallengeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2\xe9\x01\n\tChallenge\x12G\n\x06\x63reate\x12\x1c.challenges.ChallengeRequest\x1a\x1d.challenges.ChallengeResponse\"\x00\x12P\n\x0b\x62ulk_create\x12\x1c.challenges.ChallengeRequest\x1a\x1d.challenges.ChallengeResponse\"\x00(\x01\x30\x01\x12\x41\n\x04list\x12\x16.google.protobuf.Empty\x1a\x1d.challenges.ChallengeResponse\"\x00\x30\x01\x32V\n\nChallenge2\x12H\n\x06\x63reate\x12\x1d.challenges.ChallengeRequest2\x1a\x1d.challenges.ChallengeResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CHALLENGEREQUEST = _descriptor.Descriptor(
  name='ChallengeRequest',
  full_name='challenges.ChallengeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='challenges.ChallengeRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=86,
)


_CHALLENGEREQUEST2 = _descriptor.Descriptor(
  name='ChallengeRequest2',
  full_name='challenges.ChallengeRequest2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nameq', full_name='challenges.ChallengeRequest2.nameq', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=122,
)


_CHALLENGERESPONSE = _descriptor.Descriptor(
  name='ChallengeResponse',
  full_name='challenges.ChallengeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='challenges.ChallengeResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='challenges.ChallengeResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['ChallengeRequest'] = _CHALLENGEREQUEST
DESCRIPTOR.message_types_by_name['ChallengeRequest2'] = _CHALLENGEREQUEST2
DESCRIPTOR.message_types_by_name['ChallengeResponse'] = _CHALLENGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChallengeRequest = _reflection.GeneratedProtocolMessageType('ChallengeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHALLENGEREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:challenges.ChallengeRequest)
  })
_sym_db.RegisterMessage(ChallengeRequest)

ChallengeRequest2 = _reflection.GeneratedProtocolMessageType('ChallengeRequest2', (_message.Message,), {
  'DESCRIPTOR' : _CHALLENGEREQUEST2,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:challenges.ChallengeRequest2)
  })
_sym_db.RegisterMessage(ChallengeRequest2)

ChallengeResponse = _reflection.GeneratedProtocolMessageType('ChallengeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHALLENGERESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:challenges.ChallengeResponse)
  })
_sym_db.RegisterMessage(ChallengeResponse)



_CHALLENGE = _descriptor.ServiceDescriptor(
  name='Challenge',
  full_name='challenges.Challenge',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=172,
  serialized_end=405,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='challenges.Challenge.create',
    index=0,
    containing_service=None,
    input_type=_CHALLENGEREQUEST,
    output_type=_CHALLENGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='bulk_create',
    full_name='challenges.Challenge.bulk_create',
    index=1,
    containing_service=None,
    input_type=_CHALLENGEREQUEST,
    output_type=_CHALLENGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='list',
    full_name='challenges.Challenge.list',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CHALLENGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHALLENGE)

DESCRIPTOR.services_by_name['Challenge'] = _CHALLENGE


_CHALLENGE2 = _descriptor.ServiceDescriptor(
  name='Challenge2',
  full_name='challenges.Challenge2',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=407,
  serialized_end=493,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='challenges.Challenge2.create',
    index=0,
    containing_service=None,
    input_type=_CHALLENGEREQUEST2,
    output_type=_CHALLENGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHALLENGE2)

DESCRIPTOR.services_by_name['Challenge2'] = _CHALLENGE2

# @@protoc_insertion_point(module_scope)
